apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
  namespace: nginx-test
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>NGINX Test Page</title>
    </head>
    <body>
        <h1>Welcome to NGINX on Google Kubernetes!</h1>
        <p>This is a test page for the NGINX server.</p>
    </body>
    </html>
